/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CharacterEditor: typeof import('./src/components/CharacterEditor.vue')['default']
    ChatArea: typeof import('./src/components/ChatArea.vue')['default']
    GlobalNotification: typeof import('./src/components/GlobalNotification.vue')['default']
    GroupEditor: typeof import('./src/components/GroupEditor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ModelConfigDialog: typeof import('./src/components/ModelConfigDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    VectorPlugin: typeof import('./src/components/VectorPlugin.vue')['default']
    WorldbookEditor: typeof import('./src/components/WorldbookEditor.vue')['default']
  }
}
